// src/components/Greeting.jsx
import { useState } from 'preact/hooks';

export default function Greeting({ messages }) {
  const [greeting, setGreeting] = useState(messages[0]);
  const randomMessage = () => messages[(Math.floor(Math.random() * messages.length))];

  return (
    <div>
      <h3>{greeting}! Thank you for visiting!</h3>
      <button onClick={() => setGreeting(randomMessage())}>
        New Greeting
      </button>
    </div>
  )
}

// src/components/Greeting.svelte
<script>
  const { messages } = $props();

  let greeting = $state(messages[0]);
  
  const random = () => {
    return messages[(Math.floor(Math.random() * messages.length))];
  }

</script>

<div>
  <h3>{greeting}! Thank you for visiting!</h3>
  <button onclick={() => greeting = random()}>
    New Greeting
  </button>
</div>
